//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddOn
    {
        public int Id { get; set; }
        public string AddOnName { get; set; }
        public decimal AdditionalPrice { get; set; }
        public Nullable<int> UseForProductID { get; set; }
        public Nullable<decimal> QuantityUsedPerProduct { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
