//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int BatchID { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<int> IngredientID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public decimal StockLevel { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Supplier { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public decimal BatchCost { get; set; }
        public Nullable<decimal> InitialStockLevel { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
    }
}
