//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboMealVariant
    {
        public int ComboMealVariantID { get; set; }
        public Nullable<int> ComboMealID { get; set; }
        public string VariantName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ProductVariantID { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual ProductVariant ProductVariant { get; set; }
        public virtual ComboMeal ComboMeal { get; set; }
    }
}
