//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DraftOrderItem
    {
        public int DraftOrderItemId { get; set; }
        public int DraftOrderId { get; set; }
        public string ProductName { get; set; }
        public int ProductVariantId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual DraftOrder DraftOrder { get; set; }
    }
}
