//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientChangeLog
    {
        public int LogID { get; set; }
        public int IngredientID { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
    }
}
