//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.IngredientProductLinks = new HashSet<IngredientProductLink>();
            this.ProductVariantIngredients = new HashSet<ProductVariantIngredient>();
            this.StockAdjustmentLogs = new HashSet<StockAdjustmentLog>();
            this.StockLevelLogs = new HashSet<StockLevelLog>();
            this.IngredientChangeLogs = new HashSet<IngredientChangeLog>();
            this.Batches = new HashSet<Batch>();
        }
    
        public int IngredientID { get; set; }
        public string IngredientName { get; set; }
        public string BrandName { get; set; }
        public string Description { get; set; }
        public byte[] IngredientImage { get; set; }
        public Nullable<bool> IsAddOn { get; set; }
        public string TypeOfIngredient { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string AllergyInformation { get; set; }
        public string StorageConditions { get; set; }
        public Nullable<decimal> StockLevel { get; set; }
        public Nullable<decimal> LowLevel { get; set; }
        public string IngredientCategory { get; set; }
        public string MeasuringUnit { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientProductLink> IngredientProductLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariantIngredient> ProductVariantIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockAdjustmentLog> StockAdjustmentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockLevelLog> StockLevelLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientChangeLog> IngredientChangeLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
    }
}
