//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {

        public Entities()
        : base("metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=System.Data.SqlClient;provider connection string=\"data source=192.168.100.12,1433;initial catalog=TakoTea;user id=erick;password=1234;encrypt=False;MultipleActiveResultSets=True;App=EntityFramework\"")
        {
        }



        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IngredientProductLink> IngredientProductLinks { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<StockAdjustmentLog> StockAdjustmentLogs { get; set; }
        public virtual DbSet<ProductVariantIngredient> ProductVariantIngredients { get; set; }
        public virtual DbSet<ComboMealVariant> ComboMealVariants { get; set; }
        public virtual DbSet<DraftOrder> DraftOrders { get; set; }
        public virtual DbSet<StockLevelLog> StockLevelLogs { get; set; }
        public virtual DbSet<ProductVariant> ProductVariants { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<DraftOrderItem> DraftOrderItems { get; set; }
        public virtual DbSet<AddOn> AddOns { get; set; }
        public virtual DbSet<IngredientChangeLog> IngredientChangeLogs { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<ComboMeal> ComboMeals { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<OrderModel> OrderModels { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
    }
}
