//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariantIngredient
    {
        public int ProductVariantIngredientID { get; set; }
        public int ProductVariantID { get; set; }
        public int IngredientID { get; set; }
        public decimal QuantityPerVariant { get; set; }
        public string MeasuringUnit { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual ProductVariant ProductVariant { get; set; }
    }
}
