//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingsID { get; set; }
        public string LowStockThreshold { get; set; }
        public string LowStockFrequency { get; set; }
        public Nullable<bool> EnableEmailNotifications { get; set; }
        public Nullable<bool> EnableInAppNotifications { get; set; }
        public string BackupDestination { get; set; }
        public string BackupSchedule { get; set; }
        public string SavedEmails { get; set; }
        public Nullable<System.DateTime> LastBackUpDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
