//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLevelLog
    {
        public int LogID { get; set; }
        public int BatchID { get; set; }
        public int IngredientID { get; set; }
        public decimal OldStockLevel { get; set; }
        public decimal NewStockLevel { get; set; }
        public decimal QuantityChanged { get; set; }
        public string Action { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Batch Batch { get; set; }
    }
}
