//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakoTea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustmentLog
    {
        public int StockAdjustmentID { get; set; }
        public int IngredientID { get; set; }
        public decimal AdjustmentQuantity { get; set; }
        public string Reason { get; set; }
        public int UserID { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
        public decimal PreviousQuantity { get; set; }
        public decimal NewQuantity { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
    }
}
